

services:
  user-service:
    build: ./user-service
    ports:
      - "4001:4001"
    environment:
      - PORT=4001

  order-service:
    build: ./Order-service
    ports:
      - "4002:4002"
    environment:
      - PORT=4002

  food-service:
    build: ./food-service
    ports:
      - "4003:4003"
    environment:
      - PORT=4003

  api-gateway:
    build: ./api-gateway
    ports:
      - "4000:4000"
    depends_on:
      - user-service
      - order-service
      - food-service
    environment:
      - PORT=4000
networks:
  my-network:
    driver: bridge